/* Automatically generated by
	CCodeGeneratorGlobalStructure Melchor-tonel.1 uuid: e8816e38-cd03-0e00-af63-750f00364351
 */

#ifndef VMMEMORYMAP_H__
#define VMMEMORYMAP_H__
typedef struct _VMMemoryMap {
	uint64_t	oldSpaceStart;
	uint64_t	oldSpaceEnd;
	uint64_t	newSpaceStart;
	uint64_t	newSpaceEnd;
	uint64_t	allocationReserve;
	uint64_t	initialOldSpaceSize;
	uint64_t	initialNewSpaceSize;
	uint64_t	initialHeadroom;
	uint64_t	permSpaceStart;
	uint64_t	permSpaceEnd;
	uint64_t	oldSpaceMask;
	uint64_t	initialCodeZoneSize;
	uint64_t	codeZoneStart;
	uint64_t	codeZoneEnd;
	uint64_t	stackPagesStart;
	uint64_t	stackPagesEnd;
	uint64_t	initialPermSpaceSize;
	uint64_t	minPermSpaceSize;
	uint64_t	spaceMaskToUse;
	uint64_t	permSpaceMask;
	uint64_t	newSpaceMask;
 } VMMemoryMap;

#endif