/*
 * generated_stencils.hpp - Architecture dispatcher for generated stencils
 *
 * Generated by scripts/extract_stencils.py — DO NOT EDIT
 *
 * Includes the correct architecture-specific stencil header based on
 * the target platform.
 */

#ifndef PHARO_GENERATED_STENCILS_HPP
#define PHARO_GENERATED_STENCILS_HPP

#if defined(__aarch64__)
  #include "generated_stencils_arm64.hpp"
#endif

#if defined(__x86_64__)
  #include "generated_stencils_x86_64.hpp"
#endif

#endif // PHARO_GENERATED_STENCILS_HPP
