/*
 * Stencil.hpp - Stencil metadata and runtime patching
 *
 * Copyright (c) 2026 Aaron Wohl. Licensed under the MIT License.
 *
 * A "stencil" is a chunk of pre-compiled machine code (from Clang -O2)
 * with "holes" — unresolved symbol references that get patched at JIT
 * compile time. This file defines:
 *
 * 1. The relocation types we handle (ARM64 + x86_64)
 * 2. The "hole" kinds (what runtime value to patch in)
 * 3. The StencilDef struct (byte array + relocation table)
 * 4. The patch() function that fills holes with actual values
 *
 * PATCHING PROCESS (at JIT compile time):
 *
 *     1. memcpy stencil bytes into the code zone
 *     2. For each relocation in the stencil:
 *        a. Determine the hole value (continuation addr, operand, etc.)
 *        b. Encode the value into the instruction at the relocation offset
 *     3. Flush icache
 *     4. Mark the JITMethod as compiled
 */

#ifndef PHARO_STENCIL_HPP
#define PHARO_STENCIL_HPP

#include "JITConfig.hpp"
#include <cstdint>
#include <cstddef>
#include <cstring>
#include <cstdio>

#if PHARO_JIT_ENABLED

namespace pharo {
namespace jit {

// ===== HOLE KINDS =====
//
// Each relocation in a stencil references a "hole" — a symbolic name for
// a value that will be known at JIT compile time.

enum class HoleKind : uint8_t {
    Continue,       // Address of the next stencil (sequential flow)
    BranchTarget,   // Address of a branch target stencil
    Operand,        // Integer operand (e.g., variable index, literal index)
    Operand2,       // Second operand (for 2-byte extended bytecodes)
    RuntimeHelper,  // Address of a C++ runtime helper function
    ICEntry,        // Address of this send's inline cache entry
    ReturnToInterp, // Address of the interpreter re-entry stub
    ResumeAddr,     // Address of next stencil as DATA (for J2J save stack)
};

// ===== RELOCATION TYPES =====
//
// Architecture-specific instruction encodings for patching.

enum class RelocType : uint8_t {
    // ARM64 relocation types (Mach-O)
    ARM64_BRANCH26,          // b/bl: imm26 field, ±128 MB range
    ARM64_PAGE21,            // adrp: immhi:immlo encoding, ±4 GB page range
    ARM64_PAGEOFF12,         // add/ldr: imm12 field, 0-4095 byte offset in page
    ARM64_GOT_LOAD_PAGE21,   // adrp for GOT entry
    ARM64_GOT_LOAD_PAGEOFF12,// ldr from GOT entry

    // x86_64 relocation types
    X86_64_PC32,             // RIP-relative 32-bit signed offset
    X86_64_ABS64,            // Absolute 64-bit address (in data/literal pool)

    // Generic
    ABS64,                   // 64-bit absolute address (in embedded literal pool)
};

// ===== RELOCATION ENTRY =====

struct Relocation {
    uint32_t  offset;     // Byte offset within the stencil's machine code
    RelocType type;       // How the value is encoded in the instruction
    HoleKind  hole;       // What value to patch in
    int16_t   addend;     // Added to the hole value before encoding
};

// ===== STENCIL DEFINITION =====
//
// Generated by extract_stencils.py, one per bytecode handler.
// Contains the raw machine code bytes and the list of relocations.

struct StencilDef {
    const char*        name;        // Human-readable name (e.g., "pushRecvVar")
    const uint8_t*     code;        // Machine code bytes
    uint32_t           codeSize;    // Size of machine code in bytes
    const Relocation*  relocs;      // Relocation entries
    uint16_t           numRelocs;   // Number of relocation entries
    uint8_t            bytecodeLen; // How many bytecode bytes this stencil consumes
};

// ===== PATCHING =====

// Patch a single ARM64 instruction at the given location.
// `codeBase` is the start of the copied stencil in the code zone.
// `offset` is where in the stencil the instruction lives.
// `value` is the target address or immediate to encode.
inline bool patchARM64(uint8_t* codeBase, const Relocation& reloc, uint64_t value) {
    uint32_t* insn = reinterpret_cast<uint32_t*>(codeBase + reloc.offset);
    uint64_t pc = reinterpret_cast<uint64_t>(insn);

    switch (reloc.type) {
    case RelocType::ARM64_BRANCH26: {
        // b/bl: bits 25:0 = imm26 (signed, * 4 = byte offset)
        int64_t offset = static_cast<int64_t>(value) - static_cast<int64_t>(pc);
        int64_t imm26 = offset >> 2;
        if (imm26 < -(1 << 25) || imm26 >= (1 << 25)) {
            return false;  // Target too far — need trampoline (TODO)
        }
        *insn = (*insn & 0xFC000000u) | (static_cast<uint32_t>(imm26) & 0x03FFFFFFu);
        return true;
    }

    case RelocType::ARM64_PAGE21: {
        // adrp: immhi (bits 23:5) + immlo (bits 30:29)
        // Target = (PC & ~0xFFF) + (imm << 12)
        uint64_t pcPage = pc & ~0xFFFULL;
        uint64_t targetPage = value & ~0xFFFULL;
        int64_t pageDelta = static_cast<int64_t>(targetPage - pcPage) >> 12;
        if (pageDelta < -(1LL << 20) || pageDelta >= (1LL << 20)) {
            fprintf(stderr, "[JIT] ARM64_PAGE21 out of range: %lld pages\n", (long long)pageDelta);
            return false;
        }
        uint32_t immlo = (static_cast<uint32_t>(pageDelta) & 0x3) << 29;
        uint32_t immhi = (static_cast<uint32_t>(pageDelta >> 2) & 0x7FFFF) << 5;
        *insn = (*insn & 0x9F00001Fu) | immhi | immlo;
        return true;
    }

    case RelocType::ARM64_PAGEOFF12: {
        // add/ldr imm12: bits 21:10
        uint32_t pageoff = static_cast<uint32_t>(value & 0xFFF);
        // Check if this is an LDR/STR (scaled) — need to divide by access size.
        // LDR/STR unsigned offset: bits[29:24] = 111V01 where V=0 for integer.
        // In the 10-bit window (*insn >> 22), bits[7:2] = instruction bits[29:24].
        // Match 111001 (integer) or 111101 (SIMD): mask=0xEC, value=0xE4.
        uint32_t opc = (*insn >> 22) & 0x3FF;
        if ((opc & 0xEC) == 0xE4) {
            // LDR/STR unsigned offset: imm12 is scaled by access size (bits 31:30)
            uint32_t size = (*insn >> 30) & 0x3;
            pageoff >>= size;
        }
        *insn = (*insn & 0xFFC003FFu) | ((pageoff & 0xFFF) << 10);
        return true;
    }

    case RelocType::ARM64_GOT_LOAD_PAGE21:
        // Same encoding as PAGE21 but targets a GOT entry.
        // For JIT code, we eliminate the GOT indirection: patch the adrp
        // to point directly to a literal pool entry we control.
        return patchARM64(codeBase, {reloc.offset, RelocType::ARM64_PAGE21, reloc.hole, reloc.addend}, value);

    case RelocType::ARM64_GOT_LOAD_PAGEOFF12:
        // Same encoding as PAGEOFF12 but loads from GOT.
        return patchARM64(codeBase, {reloc.offset, RelocType::ARM64_PAGEOFF12, reloc.hole, reloc.addend}, value);

    default:
        break;
    }
    return false;
}

// Patch a single x86_64 instruction.
inline bool patchX86_64(uint8_t* codeBase, const Relocation& reloc, uint64_t value) {
    switch (reloc.type) {
    case RelocType::X86_64_PC32: {
        // RIP-relative 32-bit signed offset
        // The offset is relative to the END of the instruction (PC + 4)
        uint8_t* loc = codeBase + reloc.offset;
        uint64_t pc = reinterpret_cast<uint64_t>(loc) + 4;
        int64_t offset = static_cast<int64_t>(value) - static_cast<int64_t>(pc);
        if (offset < INT32_MIN || offset > INT32_MAX) {
            fprintf(stderr, "[JIT] X86_64_PC32 out of range: %lld\n", (long long)offset);
            return false;
        }
        int32_t offset32 = static_cast<int32_t>(offset);
        std::memcpy(loc, &offset32, 4);
        return true;
    }

    case RelocType::X86_64_ABS64:
    case RelocType::ABS64: {
        // Absolute 64-bit address
        uint8_t* loc = codeBase + reloc.offset;
        std::memcpy(loc, &value, 8);
        return true;
    }

    default:
        break;
    }
    return false;
}

// Patch all relocations in a copied stencil.
// `codeBase` is where the stencil was copied in the code zone.
// `resolveHole` is a callback: given a HoleKind and addend, returns the value.
template<typename ResolveFunc>
inline bool patchStencil(uint8_t* codeBase, const StencilDef& stencil, ResolveFunc resolveHole) {
    for (uint16_t i = 0; i < stencil.numRelocs; i++) {
        const Relocation& r = stencil.relocs[i];
        uint64_t value = resolveHole(r.hole, r.addend);

        bool ok;
        if constexpr (HostArch == Arch::ARM64) {
            ok = patchARM64(codeBase, r, value);
        } else {
            ok = patchX86_64(codeBase, r, value);
        }

        if (!ok) {
            fprintf(stderr, "[JIT] Failed to patch relocation %d in stencil '%s' at offset %u\n",
                    i, stencil.name, r.offset);
            return false;
        }
    }
    return true;
}

} // namespace jit
} // namespace pharo

#endif // PHARO_JIT_ENABLED
#endif // PHARO_STENCIL_HPP
