/*
 * cogmethod.h — Cog method structure definitions
 *
 * Generated by VMMaker, from Pharo-VM / OpenSmalltalk-VM.
 * Original source: https://github.com/pharo-project/pharo-vm
 * Copyright (c) 2013 3D Immersive Collaboration Consulting, LLC.
 * Licensed under the MIT License — see THIRD_PARTY_LICENSES for details.
 */

/* Automatically generated by
	MLVMCCodeGenerator Melchor-tonel.1 uuid: e8816e38-cd03-0e00-af63-750f00364351
 */

#ifndef COGMETHOD_H__
#define COGMETHOD_H__
typedef struct {
	sqLong	objectHeader;
	unsigned		cmNumArgs : 8;
	unsigned		cmType : 3;
	unsigned		cmRefersToYoung : 1;
	unsigned		cpicHasMNUCaseOrCMIsFullBlock : 1;
	unsigned		cmUsageCount : 3;
	unsigned		cmUsesPenultimateLit : 1;
	unsigned		cbUsesInstVars : 1;
	unsigned		cmUnusedFlags : 2;
	unsigned		stackCheckOffset : 12;
	unsigned short	blockSize;
	unsigned short	picUsage;
	sqInt	methodObject;
	sqInt	methodHeader;
	sqInt	selector;
 } CogMethod;
#endif