/*
 * interp.h — Generated by VMMaker, from Pharo-VM / OpenSmalltalk-VM.
 * Original source: https://github.com/pharo-project/pharo-vm
 * Copyright (c) 2013 3D Immersive Collaboration Consulting, LLC.
 * Licensed under the MIT License — see THIRD_PARTY_LICENSES for details.
 */

/* Automatically generated by
	CCodeGeneratorGlobalStructure Melchor-tonel.1 uuid: e8816e38-cd03-0e00-af63-750f00364351
 */

#ifndef INTERP_H__
#define INTERP_H__
#define VM_PROXY_MAJOR 1
#define VM_PROXY_MINOR 15

#define SQ_VI_BYTES_PER_WORD 8

#define BaseHeaderSize 8
#define BytesPerOop 8
#define BytesPerWord 8

#define PrimErrGenericFailure 1
#define PrimErrBadReceiver 2
#define PrimErrBadArgument 3
#define PrimErrBadIndex 4
#define PrimErrBadNumArgs 5
#define PrimErrInappropriate 6
#define PrimErrUnsupported 7
#define PrimErrNoModification 8
#define PrimErrNoMemory 9
#define PrimErrNoCMemory 10
#define PrimErrNotFound 11
#define PrimErrBadMethod 12
#define PrimErrNamedInternal 13
#define PrimErrObjectMayMove 14
#define PrimErrLimitExceeded 15
#define PrimErrObjectIsPinned 16
#define PrimErrWritePastObject 17
#define PrimErrObjectMoved 18
#define PrimErrObjectNotPinned 19
#define PrimErrCallbackError 20
#define PrimErrOSError 21
#define PrimErrFFIException 22
#define PrimErrNeedCompaction 23
#define PrimErrOperationFailed 24

#define MinSmallInteger -1152921504606846976
#define MaxSmallInteger 1152921504606846975
#define NumSmallIntegerTagBits 3

#if !defined(IMMUTABILITY) /* Allow this to be overridden on the compiler command line */
# define IMMUTABILITY 1
#endif /* !defined(IMMUTABILITY) */

#define STACKVM 1
#define SPURVM 1
#define COGVM 1

#endif