/*
 * vmCallback.h — FFI callback support structures
 *
 * Generated by VMMaker, from Pharo-VM / OpenSmalltalk-VM.
 * Original source: https://github.com/pharo-project/pharo-vm
 * Copyright (c) 2013 3D Immersive Collaboration Consulting, LLC.
 * Licensed under the MIT License — see THIRD_PARTY_LICENSES for details.
 *
 * Automatically generated by
 *   CCodeGeneratorGlobalStructure Melchor-tonel.1 uuid: e8816e38-cd03-0e00-af63-750f00364351
 * Modified: use sigjmp_buf for sigsetjmp/siglongjmp callback support
 */

#ifndef VMCALLBACK_H__
#define VMCALLBACK_H__
#define VM_CALLBACK_INC 1

#include <setjmp.h>

typedef struct _VMCallbackContext {
	void *thunkp;
	sqIntptr_t *stackp;
	sqIntptr_t *intregargsp;
	double *floatregargsp;
	void *savedCStackPointer;
	void *savedCFramePointer;
	union {
								sqIntptr_t valword;
								struct { int low, high; } valleint64;
								struct { int high, low; } valbeint64;
								double valflt64;
								struct { void *addr; sqIntptr_t size; } valstruct;
							}	rvs;
	void *savedPrimFunctionPointer;
	sigjmp_buf	trampoline;
	sigjmp_buf	savedReenterInterpreter;
 } VMCallbackContext;

/* The callback return type codes */
#define retword 1
#define retword64 2
#define retdouble 3
#define retstruct 4


#endif
