/*
 * vmRememberedSet.h — Generated by VMMaker, from Pharo-VM / OpenSmalltalk-VM.
 * Original source: https://github.com/pharo-project/pharo-vm
 * Copyright (c) 2013 3D Immersive Collaboration Consulting, LLC.
 * Licensed under the MIT License — see THIRD_PARTY_LICENSES for details.
 */

/* Automatically generated by
	CCodeGeneratorGlobalStructure Melchor-tonel.1 uuid: e8816e38-cd03-0e00-af63-750f00364351
 */

#ifndef VMREMEMBEREDSET_H__
#define VMREMEMBEREDSET_H__
typedef struct _VMRememberedSet {
	sqLong	fudge;
	sqLong	rootIndex;
	sqLong	rememberedSetSize;
	sqLong	rememberedSetLimit;
	sqInt *rememberedSetArray;
	sqLong	rememberedSetRedZone;
	sqLong	numRememberedEphemerons;
	sqLong	previousRememberedSetSize;
	sqLong	doFullScan;
 } VMRememberedSet;

#endif